# -*- coding: utf-8 -*-
"""Copia di PROGETTO_DI_IA2_1913071-Finale.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Jb_SfmOU8CxlJ0v93gFGJw-k_FKrnwWM
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
from google.colab import drive
drive.mount('/content/drive')

file_path = '/content/drive/My Drive/TUANDROMD.csv'
# Load the dataset
df = pd.read_csv(file_path, header=0)
# First rows
print("\n First rows:")
print(df.head().to_string())

# Define features and label
target_col = "Label"
feat_cols = [c for c in df.columns if c != target_col]

# Dataset structure
n_rows, n_cols = df.shape
print("Number of rows:", n_rows)
print("Number of columns:", n_cols)
print("Label:", target_col)

# Count and percentage of NaN for each column
missing_values = df.isnull().sum()
missing_percent = (missing_values / len(df)) * 100
missing_summary = pd.DataFrame({
    'Missing Values': missing_values,
    '% Missing': missing_percent
}).sort_values(by='% Missing', ascending=False)

print("\n Total number of nans:", len(missing_values))
print(missing_summary.head())

# Class distribution
plt.figure(figsize=(6,4))
sns.countplot(x='Label', data=df, palette='Set2')
plt.title("Label distribution (Malware vs Goodware)")
plt.xlabel("Class (1 = Malware, 0 = Goodware)")
plt.ylabel("Count")
plt.show()

# Percentage of classes
label_distribution = df['Label'].value_counts(normalize=True) * 100
print("\n Percentage distribution of labels:")
print(label_distribution)

# Feature correlation (Pearson, -1;1) with the target variable
corr = df.corr()['Label'].drop('Label').sort_values(ascending=False)
print("\n Top 10 features most correlated with the class:")
print(corr.head(10))

# Variance analysis per feature
feature_variance = df.var().sort_values(ascending=True)
low_variance = feature_variance[feature_variance == 0]
print(f"\n Number of features with zero variance: {len(low_variance)}")
if len(low_variance) > 0:
    print("Examples of constant features:")
    print(low_variance)

# Replace NaN with 0
df = df.fillna(0)
print("NaN replaced successfully!")

# Verify replacement operation
print("Number of NaN:", df.isna().sum().sum())

# Identify features with zero variance
features_zero_variance = df.var()[df.var() == 0].index.tolist()

# Remove features with zero variance from the DataFrame
df_cleaned = df.drop(columns=features_zero_variance)

# Print the count of removed features
print(f"Number of features removed due to zero variance: {len(features_zero_variance)}")
print(f"New number of columns in the DataFrame: {df_cleaned.shape[1]}")

df = df_cleaned

display(df.head())

# Calculate the correlation matrix on the entire dataset
correlation_matrix = df.drop('Label', axis=1).corr()

# Plot the correlation matrix
plt.figure(figsize=(20, 15))
sns.heatmap(correlation_matrix, cmap='coolwarm', annot=False) # annot=False to avoid overcrowding with values
plt.title('Feature Correlation Matrix (Entire Dataset)')
plt.show()

# Identify high correlations
# Find pairs of features with absolute correlation > 0.8
stacked_corr = correlation_matrix.stack()
high_corr = stacked_corr[(abs(stacked_corr) > 0.8) & (stacked_corr != 1.0)]

print("\nPairs of features with absolute correlation > 0.8:")
print(high_corr.sort_values(ascending=False).head())

# Identify highly correlated features (threshold > 0.8)
# We use an iterative approach to identify one of the features to remove in each pair
correlation_threshold = 0.8
to_drop_iterative = set()
correlation_matrix_abs = correlation_matrix.abs()

# Iterate through all pairs of features in the correlation matrix
for i in range(len(correlation_matrix_abs.columns)):
    for j in range(i + 1, len(correlation_matrix_abs.columns)):
        feature1 = correlation_matrix_abs.columns[i]
        feature2 = correlation_matrix_abs.columns[j]

        # Check if the absolute correlation between the two features is greater than the threshold
        if correlation_matrix_abs.iloc[i, j] > correlation_threshold:
            # If the correlation is high, add one of the two features to the set to be removed
            # In this case, we add the second feature of the pair (feature2)
            to_drop_iterative.add(feature2)

# Convert the set to a list for column removal
to_drop = list(to_drop_iterative)

print(f"Number of features to remove due to high multicollinearity (> {correlation_threshold}): {len(to_drop)}")
print("Features to remove:")
print(to_drop)

# Remove the identified features
df_final = df.drop(columns=to_drop)

print("\nDataFrame dimensions after removing highly correlated features:")
print(f"DataFrame (df_final): {df_final.shape}")

from sklearn.model_selection import train_test_split

# Define features (X) and target (y)
X = df_final.drop('Label', axis=1)
y = df_final['Label']

# Split the dataset into training (70%) and a temporary set (30%)
X_train, X_temp, y_train, y_temp = train_test_split(X, y, test_size=0.3, random_state=42, stratify=y)

# Split the temporary set into validation (50% of temporary, i.e., 15% of total) and test (50% of temporary, i.e., 15% of total)
X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=0.5, random_state=42, stratify=y_temp)

print("Dimensions of the sets after splitting:")
print(f"Training set (X_train, y_train): {X_train.shape}, {y_train.shape}")
print(f"Validation set (X_val, y_val): {X_val.shape}, {y_val.shape}")
print(f"Test set (X_test, y_test): {X_test.shape}, {y_test.shape}")

# Verify class distribution maintenance in each set
print("\nClass distribution in sets:")
print("Train set:")
print(y_train.value_counts(normalize=True))
print("\nValidation set:")
print(y_val.value_counts(normalize=True))
print("\nTest set:")
print(y_test.value_counts(normalize=True))

from sklearn.model_selection import cross_val_score, StratifiedKFold, cross_validate
from sklearn.linear_model import LogisticRegression

# Logistic Regression model with class_weight='balanced'
# We use solver='liblinear' which by default has L2 regularization
model_cv = LogisticRegression(random_state=42, solver='liblinear', class_weight='balanced')

# Define the cross-validation strategy with 5 splits
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

# Execute cross-validation
scoring = ['accuracy', 'precision', 'recall', 'f1', 'roc_auc']
cv_results = cross_validate(model_cv, X_train, y_train, cv=cv, scoring=scoring)

# Print results
print("Cross-Validation Results (class_weight='balanced'):")
for metric in scoring:
    mean_score = np.mean(cv_results[f'test_{metric}'])
    std_score = np.std(cv_results[f'test_{metric}'])
    print(f"{metric.capitalize()} mean (± standard deviation): {mean_score:.4f} ± {std_score:.4f}")

# For reference, also print scores for each fold
print("\nScores for each fold:")
for metric in scoring:
    print(f"{metric.capitalize()}: {cv_results[f'test_{metric}']}")

from imblearn.pipeline import Pipeline
from imblearn.over_sampling import SMOTE

# Cross-validation strategy same as before
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

# Define Logistic Regression model (without class_weight='balanced' in this case,
# as SMOTE handles balancing)
model_lr = LogisticRegression(random_state=42, solver='liblinear')

# Define pipeline: 1) Apply SMOTE 2) Train
pipeline = Pipeline([
    ('smote', SMOTE(random_state=42)),
    ('logistic', model_lr)
])

# Metrics for evaluation
scoring = ['accuracy', 'precision', 'recall', 'f1', 'roc_auc']

# Execute cross-validation on the pipeline
cv_results_smote = cross_validate(pipeline, X_train, y_train, cv=cv, scoring=scoring)

print("Cross-Validation Results (SMOTE inside folds):")
for metric in scoring:
    mean_score = np.mean(cv_results_smote[f'test_{metric}'])
    std_score = np.std(cv_results_smote[f'test_{metric}'])
    print(f"{metric.capitalize()} mean (± standard deviation): {mean_score:.4f} ± {std_score:.4f}")

# For reference, also print scores for each fold
print("\nScores for each fold:")
for metric in scoring:
    print(f"{metric.capitalize()}: {cv_results_smote[f'test_{metric}']}")

print("Comparison of Cross-Validation results:")

# Metrics for comparison
scoring = ['accuracy', 'precision', 'recall', 'f1', 'roc_auc']

# Collect data for comparison
comparison_data = {}

for metric in scoring:
    mean_cw = np.mean(cv_results[f'test_{metric}'])
    std_cw = np.std(cv_results[f'test_{metric}'])
    mean_smote = np.mean(cv_results_smote[f'test_{metric}'])
    std_smote = np.std(cv_results_smote[f'test_{metric}'])

    comparison_data[metric.capitalize()] = {
        'LogReg (class_weight=balanced) - Mean': f"{mean_cw:.4f}",
        'LogReg (class_weight=balanced) - Std Dev': f"{std_cw:.4f}",
        'LogReg (SMOTE) - Mean': f"{mean_smote:.4f}",
        'LogReg (SMOTE) - Std Dev': f"{std_smote:.4f}"
    }

# Convert the dictionary to a DataFrame for clearer visualization
comparison_df = pd.DataFrame(comparison_data).T

display(comparison_df)

# Apply SMOTE exclusively to the training set
smote = SMOTE(random_state=42)
X_train_res, y_train_res = smote.fit_resample(X_train, y_train)

print("Training set dimensions after SMOTE:")
print(f"Training set (X_train_res, y_train_res): {X_train_res.shape}, {y_train_res.shape}")

# Verify class distribution after SMOTE
print("\nClass distribution in the training set after SMOTE:")
print(y_train_res.value_counts(normalize=True))

# Initialize Logistic Regression model
# We keep the parameters used during cross-validation
model = LogisticRegression(random_state=42, solver='liblinear')

# Train the model on the resampled training set
model.fit(X_train_res, y_train_res)

print('Training Logistic Regression model...')
print("Logistic Regression model trained successfully.")

# Feature importance analysis (Logistic Regression model coefficients)

# Get the model coefficients.
coefficients = model.coef_[0]

# Get feature names ensuring the order matches the coefficients.
feature_names = X_train_res.columns

# Create a Pandas Series to associate coefficients with feature names
feature_importance = pd.Series(coefficients, index=feature_names)

# Sort features in descending order based on the absolute value of coefficients to find the most important ones
sorted_feature_importance = feature_importance.abs().sort_values(ascending=False)

print("Top 10 Features by Importance (based on absolute value of Logistic Regression coefficients):")
print(sorted_feature_importance.head(10))

# Graphical visualization
plt.figure(figsize=(10, 6))
sorted_feature_importance.head(10).plot(kind='barh')
plt.title('Feature Importance (Top 10)')
plt.xlabel('Absolute Value of Logistic Regression Coefficient')
plt.ylabel('Feature')
plt.gca().invert_yaxis()
plt.show()

from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, roc_curve, roc_auc_score

# Predictions on the test set
y_pred_test = model.predict(X_test)

# Performance evaluation
print("Classification Report on Test Set:")
print(classification_report(y_test, y_pred_test))

cm_test = confusion_matrix(y_test, y_pred_test)

print("\nAccuracy on Test Set:")
print(accuracy_score(y_test, y_pred_test))

# Confusion matrix plot on the test set
plt.figure(figsize=(8, 6))
sns.heatmap(cm_test, annot=True, fmt='d', cmap='Blues', cbar=False,
            xticklabels=['Predicted 0', 'Predicted 1'],
            yticklabels=['Actual 0', 'Actual 1'])
plt.title('Confusion Matrix (Test Set)')
plt.xlabel('Predicted Value')
plt.ylabel('True Value')
plt.show()

# ROC curve and AUC on the Test Set
# Get prediction probabilities for the positive class on the test set
y_pred_proba_test = model.predict_proba(X_test)[:, 1]

# Calculate ROC curve
fpr, tpr, thresholds = roc_curve(y_test, y_pred_proba_test)

# Calculate AUC
auc = roc_auc_score(y_test, y_pred_proba_test)

print(f"\nAUC on Test Set: {auc:.4f}")

# Display ROC curve
plt.figure(figsize=(8, 6))
plt.plot(fpr, tpr, color='darkorange', lw=2, label=f'ROC Curve (AUC = {auc:.4f})')
plt.plot([0, 1], [0, 1], color='navy', lw=2, linestyle='--', label='Random')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve (Test Set)')
plt.legend(loc='lower right')
plt.grid(True)
plt.show()

# Verify the number of iterations (epochs) taken for convergence
# of the model trained with SMOTE
print(f"The Logistic Regression model (with SMOTE) converged in {model.n_iter_[0]} iterations.")